//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data.Item
{
    using System;
    using System.Collections.Generic;
    
    
    public class Item
    {
        
        // ID

        public double Id {get;set;}

        // 道具
        public string Name {get;set;}
        // 类型
        public double Type {get;set;}
        // 描述
        public string Des {get;set;}
    }
}
