//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data.Mail
{
    using System;
    using System.Collections.Generic;
    
    
    public class Mail
    {
        
        // ID

        public double Id {get;set;}

        // 邮件类型
        public double type {get;set;}
        // 邮件状态
        public double state {get;set;}
        // 是否已读
        public double read {get;set;}
        // 名字
        public double name {get;set;}
        // 内容
        public double content {get;set;}
        // 链接
        public double link {get;set;}
    }
}
