//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data.Shop
{
    using System;
    using System.Collections.Generic;
    
    
    public class Shop
    {
        
        // id

        public double Id {get;set;}

        // itemId
        public double ItemId {get;set;}
        // 数量
        public double Count {get;set;}
        // 价格
        public double Price {get;set;}
        // 类型
        public double Type {get;set;}
    }
}
